name: bangla_handwritten_math_solver_flutter_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  beamer: ^1.5.3
  cached_network_image: ^3.2.2
  file_picker: ^5.2.2
  file_saver: ^0.1.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  logger: ^1.1.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.13
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_icons:
  image_path: "assets/icons/flutter_logo.png"
  android: true
  ios: true
  # command: flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/flutter_logo.png"
  android: true
  ios: true
  web: true
  # command: flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/svgs/
